spring:
  application:
    name: department-v1
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
    name: department-v1,common

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka server URL
    fetch-registry: true # Fetch service registry from Eureka
    register-with-eureka: true # Register this service with Eureka
    instance:
      preferIpAddress: true


management:
  endpoints:
    web:
      exposure:
        include: refresh
